### ISSUE TITLE
isOS undefined

### ISSUE THREAD

**Issue by sertonix** [arkenfox/TZP#332]
TZP is unable to determine my OS :sunglasses: 

I changed the `font-family` to `sans-serif`. And `get_font_sizes` results in an empty array (haven't checked why).

Maybe fall back to a dump `navigator.platform` check in `trysomethingelse`?

**Comment by Thorin-Oakenpants** [comment]
where did you change the font-family

**Comment by Thorin-Oakenpants** [comment]
if isOS is undefined, then font lists are not created and we do not run font_sizes/font_names tests - because they rely on specific lists _per_ OS
- https://github.com/arkenfox/TZP/blob/ae28c16940635c51fbae5041153f10a68a47ae9d/js/fonts.js#L499
- https://github.com/arkenfox/TZP/blob/ae28c16940635c51fbae5041153f10a68a47ae9d/js/fonts.js#L885-L887

**Comment by sertonix** [comment]
> where did you change the font-family

Testing around a bit I have no idea what caused the change.

> also what OS - and language/locale?

It's linux and en-US.

**Comment by Thorin-Oakenpants** [comment]
well, if I don't know what you did I can't do much about it. I do not want to rely on anything the browser or extensions can lie about - if someone fucks up that bad then I'd rather produce no fonts at all - not interested in outliers, more interested in non-noisy data

OK, so the first step is `trywidgets`. If the font name is a generic font-family (or undefined etc) then we move to `tryfonts`
https://github.com/arkenfox/TZP/blob/4e1570a2c424a81123aafbd07d55a4eefc58cbc0/js/generic.js#L339-L340

otherwise we default to linux and then fixup if windows/mac/android
https://github.com/arkenfox/TZP/blob/4e1570a2c424a81123aafbd07d55a4eefc58cbc0/js/generic.js#L339-L342

So I can only surmise you had RFP enabled and we are falling back to `tryfonts`. For linux I don't have a font I can test for - on windows and mac and android I have expected system fonts that cannot be blocked (aside from blocking document fonts), namely these:

https://github.com/arkenfox/TZP/blob/4e1570a2c424a81123aafbd07d55a4eefc58cbc0/js/fonts.js#L430-L434

The mini font test for OS doesn't care about generic font families, you can any as your default. It will check against all three with fallbacks - here's what it will test against
https://github.com/arkenfox/TZP/blob/4e1570a2c424a81123aafbd07d55a4eefc58cbc0/js/fonts.js#L805-L806

and it will compare until detected
https://github.com/arkenfox/TZP/blob/4e1570a2c424a81123aafbd07d55a4eefc58cbc0/js/fonts.js#L896

here, on windows, for this example, I have disabled the exit when found part (isDetected) and forced it to do all three checks
![example](https://github.com/user-attachments/assets/9fb5fb46-6a01-4fb6-920f-5824fbfc2e17)

You're on linux, but unless on windows, you set Tahoma as your default font for all three, something has to be found .. etc.

Assuming we run the font test, then like widgets, we kinda default to `linux` and fixup with android, windows or mac
https://github.com/arkenfox/TZP/blob/4e1570a2c424a81123aafbd07d55a4eefc58cbc0/js/generic.js#L309-L315

if we only get 1 result (the test includes a fake font name) and it matches windows/mac/android then voila, otehrwise if we get nothing then it must be linux.

The only way it cannot be linux is
- you have disabled document fonts
- you return more than 1 result

In which case you're an outlier

**Comment by sertonix** [comment]
It's a TZP but. MR in progress...

**Comment by sertonix** [comment]
`typeFn(res)` was returning `empty array` on linux which didn't equal `array` (#334)

**Comment by Thorin-Oakenpants** [comment]
well, fuck - thanks. I was about to test TB14 on linux and this would have shown up .. so you beat me to it. It's not like I run RFP tests on linux all the time (and TB13 uses the chrome:// check for OS)
